language: node_js
sudo: false
branches:
  only:
    - master
before_install:
- gem install scss_lint
script:
- npm run build --release
node_js:
- '4.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
- chmod a+x ./tasks/deploy.sh
- ./tasks/deploy.sh
